/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electronwebviewtest;

import java.io.IOException;

/**
 *
 * @author bruno
 */
public class Test extends javax.swing.JFrame {

    private ButtonsControl buttonsControl;
    private SocketServer app = null;

    /**
     * Creates new form Test
     */
    public Test() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                frameInitialization();
            }
        }).start();
    }

    private void frameInitialization() {
        initComponents();
        buttonsControl = new ButtonsControl(this);

        this.getRootPane().setDefaultButton(btnSend);
    }

    private void createServer() throws IOException {

        try {
            app = new SocketServer(Constants.HOST);
        } catch (Exception ex) {
        }
        if (app != null) {
            System.out.println("\r\nRunning Server: "
                    + "Host=" + app.getSocketAddress().getHostAddress()
                    + " Port=" + app.getPort());
        } else {
            System.out.println("Server null");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        openBtn = new javax.swing.JButton();
        tfMessage = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        close = new javax.swing.JButton();
        messageLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Server");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        backPanel.setBackground(new java.awt.Color(255, 255, 255));
        backPanel.setMaximumSize(new java.awt.Dimension(399, 299));
        backPanel.setMinimumSize(new java.awt.Dimension(399, 299));
        backPanel.setPreferredSize(new java.awt.Dimension(399, 299));

        openBtn.setText("Open");
        openBtn.setFocusPainted(false);
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });

        btnSend.setText("Send");
        btnSend.setFocusPainted(false);
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        close.setText("Close");
        close.setFocusPainted(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        messageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(openBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backPanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(tfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(messageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(openBtn)
                .addGap(18, 18, 18)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(close)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
        try {
            createServer();
        } catch (IOException ex) {
        }

        new Thread(new Runnable() {
            @Override
            public void run() {
                setOpenBtnEnabled(false);
                buttonsControl.openElectron();
                buttonsControl.socketListen(app);
            }
        }).start();
    }//GEN-LAST:event_openBtnActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        if (app != null && !app.getSocket().isClosed()) {
            String message = tfMessage.getText();
            if (!message.trim().isEmpty()) {
                buttonsControl.sendMessage(app, message);
            }
            tfMessage.setText("");
            tfMessage.requestFocus();
        } else {
            System.out.println("Socket null");
            this.setMessageLblText("Não há conexões");
            tfMessage.setText("");
            tfMessage.requestFocus();
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        buttonsControl.endConnection(app);
    }//GEN-LAST:event_closeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton close;
    private javax.swing.JLabel messageLbl;
    private javax.swing.JButton openBtn;
    private javax.swing.JTextField tfMessage;
    // End of variables declaration//GEN-END:variables

    public void setMessageLblText(String message) {
        messageLbl.setText(message);
    }
    
    public void setOpenBtnEnabled(boolean enable) {
        openBtn.setEnabled(enable);
    }
}
